module.exports={
    usertype:{
        admin:"Admin",
        student:"Student",
        hr:"HR"
    },
    userstatus:{
        approved:"Approved",
        pending:"Pending",
        rejeceted:"Rejected"
    }
}